### ISSUE TITLE
SIgnIn not being resolved

### ISSUE THREAD

**Issue by taivo1** [inouiw/capacitor-native-google-one-tap-signin#25]
Here 

https://github.com/inouiw/capacitor-native-google-one-tap-signin/blob/16485787309e806d2c0dba9d4f01d99719a653f9/src/web/GoogleIdentityServicesClient.ts#L60

and here:

https://github.com/inouiw/capacitor-native-google-one-tap-signin/blob/16485787309e806d2c0dba9d4f01d99719a653f9/src/web/GoogleIdentityServicesClient.ts#L53

the promise is not being handled, maybe it should reject the promise.

I'm having issues when calling tryAutoOrOneTapSignInWithCallback in Web, it just keeps hanging there once I close the dialog.

```
// Trigger auto sign-in and if not successful try one-tap sign-in. Pass a callback.
await GoogleOneTapAuth.tryAutoOrOneTapSignInWithCallback(onResultHandler);
// this line is never reached due to the previous call is not resolved so the button is not initialized.
// Add a handler to the button shown below. Pass a callback.
await GoogleOneTapAuth.addSignInActionToExistingButtonWithCallback(
  'google-signin-existing-btn-parent', 'google-signin-existing-btn', onResultHandler);
```

**Comment by inouiw** [comment]
Hi @taivo1 ,

thank you for posting the issue and for using the plugin.
I will check tonight if I can find the error. Currently I am wonderning why the callback method is async. This could explain why the callback is not called. You can try to call tryAutoOrOneTapSignInWithCallback without await.

David

**Comment by inouiw** [comment]
Hi @taivo1 ,

I tested the code in the demo app and it is working. awaiting the method is correct because it ensures that you get feedback if there is an exception.

Before calling `await GoogleOneTapAuth.addSignInActionToExistingButtonWithCallback('google-signin-existing-btn-parent', 'google-signin-existing-btn', onResult);`, you need to call `GoogleOneTapAuth.initialize({ clientId: clientId });`, but I assume you did it because you would get an error result displayed in the developer console if not.

It could be an issue how you defined the existing button. In the demo project it is as follows.
```
<div id='google-signin-existing-btn-parent'>
    <button id='google-signin-existing-btn' style={{ padding: 20, backgroundColor: '#3dc418' }}>Custom Sign-in Button</button>
</div>
```
see https://github.com/inouiw/capacitor-native-google-one-tap-signin/blob/main/demo/react/src/pages/Page1.tsx

If this did not help, mybe you could provide more of your code.

**Comment by inouiw** [comment]
Hi @taivo1,
there were some promises that did not return in case of an exception. I fixed that. Would be great if you could check if you get a proper error result now. The version that includes the fix is 6.1.7

**Comment by taivo1** [comment]
Thanks, after quick testing with my app facing still the same issue, but will try to get you more proper example of my use case in a few days.

**Comment by taivo1** [comment]
How I'm testing the auth flow is like this:

1. On first page load I call the init the auth client and tryAutoOrOneTapSignInWithCallback
2. This Google auth screen will pop up on top right -Instead of tapping on my account I will **close the dialog from the X** button on corner 
![Screenshot 2024-10-28 at 20 38 56](https://github.com/user-attachments/assets/2f426ba1-d08a-4840-8906-4e24d5f2abdb)
3. I'll reload the page and same process should repeat but now the promise is not resolved and callback not firing at all and the Google auth screen will not appear anymore.

Tried the demo app and looks like the same thing happened with demo app. So once I close/cancel the google dialog the only thing I can do it click the google signin button but would be nice to know from the promise that I would need to intialize the button.

**Comment by inouiw** [comment]
Hi @taivo1,
most likely the "show third-party sign-in prompts" setting has been disabled automatically by the browser because of the cancel. You can re-enable it in chrome under chrome://settings/content/federatedIdentityApi

Because the prompt can be disabled, it is best to show the popup and the button at the same time. I have not been able to detect if the prompt is disabled. Maybe you can find a way.
